name: rawrz-security-platform
services:
- name: api
  source_dir: /
  github:
    repo: ItsMehRAWRXD/itsmehrawrxd
    branch: master
  run_command: node api-server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
  - key: JOTTI_API_URL
    value: "https://virusscan.jotti.org"
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3