name: rawrzapp
services:
- name: web
  source_dir: /
  github:
    repo: ItsMehRAWRXD/itsmehrawrxd
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: AUTH_TOKEN
    value: "rawrz-secure-token-2024"
  - key: GITHUB_TOKEN
    value: "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"
  - key: DIGITAL_OCEAN_TOKEN
    value: "dop_v1_ccce0b4c48181e9ef566a7b2a5105194256b8302af99761a7cad6d3007c4e"
  build_command: npm install
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3